Validate recipient email addresses to prevent invalid ending characters
thunderbird/thunderbird-android pull request #8020
Opened 2024-07-22 22:01 UTC by mhf1998

Fixes #7112 

- Added a regular expression pattern to identify and invalidate email addresses that end with specific invalid characters.
- The validation logic was incorporated into the `isValidEmail` method, ensuring that any email address ending with characters such as `/`, `?`, `=`, `+`, `&`, `^`, `%`, `$`, `#`, `!`, `'`, and `-` is correctly flagged as invalid. (I checked and all the special characters that led to the repeating of this bug scenario were just these.)
- Improved error handling, and show an error when the focus is changed from the To, CC, and BCC fields; instead of showing the error after sending the email.

![image](https://github.com/user-attachments/assets/8df0dc77-f629-40a5-abef-53e2c671eb53)

2024-07-23 14:05 UTC, cketti requested changes
Please add an additional (in)validity check for the domain part to `UserInputEmailAddressParser` and add relevant tests to `UserInputEmailAddressParserTest`.

Side note: This doesn't fix the underlying problem of us (indirectly) using `Rfc822Tokenizer` which is a bad fit for the job. However, it does improve the current situation a little bit.

2024-07-24 00:34 UTC, mhf1998 commented on legacy/ui/legacy/src/main/java/com/fsck/k9/view/RecipientSelectView.java
> +        Pattern invalidEndingPattern = Pattern.compile("[/?=+&^%$#!'\\-]$");
> A quick test revealed that adding e.g. a slash in the middle of the domain part is currently also considered valid by `UserInputEmailAddressParser`. Example: `test@domain/example`.
> 
> So only checking the last character of the domain part is not sufficient to catch all instances of this bug. I suggest using `HostNameUtils.isLegalHostNameOrIP()` to validate the domain part of the entered email address.

I read everything you mentioned. Got it. 
I'll get it all done at the first chance I get.

2024-07-24 01:01 UTC, mhf1998 commented on legacy/ui/legacy/src/main/java/com/fsck/k9/view/RecipientSelectView.java
> +            if (!isValidEmail(parsedAddresses)) {
Done!

2024-07-24 01:01 UTC, mhf1998 commented on legacy/ui/legacy/src/main/java/com/fsck/k9/view/RecipientSelectView.java
> +        Pattern invalidEndingPattern = Pattern.compile("[/?=+&^%$#!'\\-]$");
Done!

2024-07-24 01:17 UTC, mhf1998 commented
I have implemented everything you asked for. Now, the domain is correctly validated by the use of the function you mentioned, and even if the last character of the email is wrong, that is caught as well, and the relevant error is displayed. 
Moreover, all tests have been written and added to the class.

2024-07-26 11:13 UTC, cketti commented on legacy/ui/legacy/src/main/res/values-fa/strings.xml
> +    <string name="recipient_error_invalid_email">آدرس ایمیل نامعتبر است</string>
Translations should only be updated via Weblate. Changing them in a pull request leads to the potential for merge conflicts in Weblate that are annoying to fix.

2024-07-30 12:20 UTC, mhf1998 commented
@cketti
I have implemented everything you asked for. Done.

2024-07-30 20:45 UTC, cketti approved these changes

2024-07-30 20:45 UTC, merged

2024-07-30 20:45 UTC, cketti commented
Thanks :+1:

2024-07-30 23:25 UTC, mhf1998 commented
You're welcome.
It's an honor to collaborate on this project. ☺️
Thank you for taking the time to review and respond.🙏🏻