Fix a crash that occurs when the password input field visibility state changes and an accessibility service is enabled
thunderbird/thunderbird-android pull request #8071
Opened 2024-08-18 23:53 UTC by muqeeta96

This pull request addresses a specific issue: our app crashes when the password visibility state changes while an accessibility service is enabled. The crash is due to an existing issue between the accessibility service, Jetpack Compose, and how these components interact.

This issue is explained in this ticket #7705. The crash initially manifested in a specific part of the app. However, further investigation revealed that this issue can occur in any part of the app where the password field is used and an accessibility service is active.

**Issue:**
- The problem occurs when an accessibility service (e.g., TalkBack) is active, and the user toggles the visibility of a password field. This interaction triggers conflicting accessibility events, leading to a crash.

**Fix:**

- I've applied Modifier.clearAndSetSemantics { } to the password field as a temporary solution. This clears and resets the semantics of the composable, preventing conflicting events and avoiding the crash.

2024-08-21 16:04 UTC, cketti requested changes
Thanks for working on this :heart: 

In my tests the app didn't crash on Android 8 and above. So I think this work-around can be limited to Android 7 (and below, since I wasn't able to get Talkback working in emulators prior to Android 7.1).

Unfortunately, this change currently only fixes the password input in the server settings screens. It doesn't fix the password input in the automatic account setup flow. The work-around should probably be moved further down. I think the `TextFieldOutlinedPassword` implementations are a good place for it.

2024-08-23 09:18 UTC, muqeeta96 commented
Ok. I will make the changes today.

2024-08-26 12:11 UTC, cketti requested changes
Thanks for updating the pull request :+1: 

There's some [code style violations](https://github.com/thunderbird/thunderbird-android/actions/runs/10529394461/job/29198576672?pr=8071#step:6:57). You should be able to automatically fix them using `gradlew spotlessApply`.

Please rewrite the history of your branch to be based on the current state of the `main` branch and only contains one commit with your change. This will make it easier for us to merge your change. If you need help with that, please let me know.

2024-08-26 12:11 UTC, cketti commented on core/ui/compose/designsystem/src/main/kotlin/app/k9mail/core/ui/compose/designsystem/atom/textfield/TextFieldOutlinedPassword.kt
> +    * resetting the semantics of the composable.
The comment needs to be updated to reflect the new code. It should probably also include a link to the relevant Google issue: https://issuetracker.google.com/issues/348232635

2024-08-27 11:06 UTC, muqeeta96 commented
I mistakenly merge it. But now I fixed it with a rebase and pushed it.

2024-08-28 12:23 UTC, merged

2024-08-28 12:23 UTC, cketti commented
Thank you :+1: