Fix bug #8073
thunderbird/thunderbird-android pull request #8081
Opened 2024-08-25 10:26 UTC by SuGotLand

fix [#8073 ](https://github.com/thunderbird/thunderbird-android/issues/8073)

2024-08-26 12:19 UTC, cketti requested changes
Thanks for your patch :heart: 

It requires a few minor tweaks before it's ready to be merged.

2024-08-26 12:19 UTC, cketti commented on legacy/ui/legacy/src/main/java/com/fsck/k9/ui/settings/account/OpenPgpAppSelectDialog.java
> +            //dismiss();
Please remove old code instead of commenting it out.

2024-08-26 12:19 UTC, cketti commented on legacy/ui/legacy/src/main/java/com/fsck/k9/ui/settings/account/OpenPgpAppSelectDialog.java
> +                    dismissAllowingStateLoss();
The onClick-handler should only be called when the activity is still active. So calling `dismissAllowingStateLoss()` here is not necessary. Please revert this change.

2024-08-26 12:19 UTC, cketti commented on legacy/ui/legacy/src/main/java/com/fsck/k9/ui/settings/account/OpenPgpAppSelectDialog.java
> +                    dismissAllowingStateLoss();
The onClick-handler should only be called when the activity is still active. So calling `dismissAllowingStateLoss()` here is not necessary. Please revert this change.

2024-08-27 15:41 UTC, SuGotLand commented
I have changed the code by your suggestion.

2024-08-28 12:30 UTC, cketti requested changes
- Please update the branch to remove unnecessary white space changes (see GitHub's diff view).
- Please use a more descriptive commit message, e.g. "Fix crashes in crypto provider selection dialogs".
- Please rewrite your branch to only contain one commit with the final change.

If you need help with any of that, please let us know and we can provide more detailed instructions.

2024-08-30 07:59 UTC, SuGotLand commented
I've deleted the unnecessary white space, but I don't know how to change the branch that only contain one commit with the final change.

2024-08-30 10:51 UTC, cketti commented
To get rid of merge commits and combine your individual commits into one, an interactive rebase can be used: `git rebase -i main`. https://git-scm.com/docs/git-rebase has more information.

I've fixed up this branch for you. Once the CI jobs have completed, this PR should be ready to be merged.

2024-08-30 10:51 UTC, cketti approved these changes

2024-08-30 10:56 UTC, merged

2024-08-30 10:56 UTC, cketti commented
Thank you for your contribution :+1: