Disable Unified Inbox if there's only one account
thunderbird/thunderbird-android pull request #8459
Opened 2024-10-31 14:54 UTC by shamim-emon

- Disable Unified Inbox by default.
- Enable Unified Inbox Automatically when Additional Account Included .

Fixes #7556

2024-11-05 11:08 UTC, shamim-emon commented
@cketti @wmontwe could you please take a look and let me know if any feedback.
Thanks in advance

2024-11-05 16:58 UTC, wmontwe requested changes
I suggest moving the logic for controlling `isShowUnifiedInbox` to `com.fsck.k9.account.AccountCreator`. Since the account is persisted after a successful call to `AccountCreator.create()`, this is the ideal place to handle this setting.

2024-11-06 02:07 UTC, shamim-emon commented
> I suggest moving the logic for controlling `isShowUnifiedInbox` to `com.fsck.k9.account.AccountCreator`. Since the account is persisted after a successful call to `AccountCreator.create()`, this is the ideal place to handle this setting.

@wmontwe Done!

2024-11-06 12:37 UTC, wmontwe reviewed
Why is it necessary to use a dedicated PreferenceDataStore for these settings instead of modifying K9's settings directly?

Also, please combine your commits into a single one. The current structure is fine otherwise.

2024-11-06 13:02 UTC, shamim-emon commented
> Why is it necessary to use a dedicated PreferenceDataStore for these settings instead of modifying K9's settings directly?
> 
> Also, please combine your commits into a single one. The current structure is fine otherwise.

@wmontwe got rid of the dedicated `PreferenceDataStore  `and modifying K9's settings directly

2024-11-06 13:36 UTC, cketti commented
When changing the default value of a setting, this should be reflected in the associated "settings description". In this case: https://github.com/thunderbird/thunderbird-android/blob/2c550badeda212c8cab4696b16df58830c60b660/legacy/core/src/main/java/com/fsck/k9/preferences/GeneralSettingsDescriptions.java#L173-L175

Steps that need to be performed:
1. Increment [`Settings.VERSION`](https://github.com/thunderbird/thunderbird-android/blob/2c550badeda212c8cab4696b16df58830c60b660/legacy/core/src/main/java/com/fsck/k9/preferences/Settings.java#L36) 
2. Add a line to the `showUnifiedInbox` entry in `GeneralSettingsDescriptions` using the new version number and default value.

Unfortunately, the QR code import from Thunderbird desktop currently doesn't use `AccountCreator`. So even if users import more than one account from Thunderbird desktop, the unified inbox will stay disabled. 
I don't think this has to be fixed right away. But we should create an issue to keep track of this.

2024-11-06 14:00 UTC, shamim-emon commented
> When changing the default value of a setting, this should be reflected in the associated "settings description". In this case:
> 
> https://github.com/thunderbird/thunderbird-android/blob/2c550badeda212c8cab4696b16df58830c60b660/legacy/core/src/main/java/com/fsck/k9/preferences/GeneralSettingsDescriptions.java#L173-L175
> 
> Steps that need to be performed:
> 
> 1. Increment [`Settings.VERSION`](https://github.com/thunderbird/thunderbird-android/blob/2c550badeda212c8cab4696b16df58830c60b660/legacy/core/src/main/java/com/fsck/k9/preferences/Settings.java#L36)
> 2. Add a line to the `showUnifiedInbox` entry in `GeneralSettingsDescriptions` using the new version number and default value.
> 
> Unfortunately, the QR code import from Thunderbird desktop currently doesn't use `AccountCreator`. So even if users import more than one account from Thunderbird desktop, the unified inbox will stay disabled. I don't think this has to be fixed right away. But we should create an issue once this PR is merged to keep track of this problem.

@cketti done, hope I got #2 right?
Also, I will create an issue for Thunderbird desktop once this PR is merged.

2024-11-06 14:13 UTC, cketti commented
@shamim-emon: Please undo the unrelated formatting changes. They bury the actual changes.

2024-11-06 15:40 UTC, shamim-emon commented
> @shamim-emon: Please undo the unrelated formatting changes. They bury the actual changes.

@cketti done!

2024-11-07 12:25 UTC, shamim-emon commented
@cketti @wmontwe please let me know if anymore changes required and/ or if I have missed anything. 
Thanks!

2024-11-07 13:29 UTC, wmontwe commented
Added issue to track missing QR code changes: #8531

Could you please squash your changes into one commit and update this pull-request. Then it's ready.

2024-11-07 15:14 UTC, wmontwe approved these changes
Thank you 👍

2024-11-07 16:06 UTC, merged