[Feature]Always mark read when archiving email messages
thunderbird/thunderbird-android pull request #8602
Opened 2024-11-22 12:00 UTC by shamim-emon

- Always mark read when archiving email messages
-Fixed #8309

2024-11-25 14:35 UTC, cketti requested changes
Please check [this comment](https://github.com/thunderbird/thunderbird-android/issues/8309#issuecomment-2498120918) for additional requirements for this behavior change.

Unfortunately, this change doesn't achieve the desired effect.
1. `MessagingController.moveOrCopyMessageSynchronous()` is used for all move operations, not just for moving a message to the archive folder. However, we don't want all moved messages to automatically be marked as read.
2. Calling `setFlag()` on a `LocalMessage` instance will only mark the message as read locally, not on the server.

`MessagingController` always changes the local message state first, then enqueues a "command" that will perform the message changes on the server. By separating local changes from remote changes the app can be used offline. When connectivity returns the queue of remote operations will be processed.

There's already `MoveOrCopyFlavor.MOVE_AND_MARK_AS_READ`. Previously, there was no reason for `MessagingController.moveOrCopyMessageSynchronous()` to support this functionality. Now, adding support for `MOVE_AND_MARK_AS_READ` to this method would make it trivial to then change the behavior of only the archive action.

Please feel free to ask in the developer Matrix room if you have questions on any of this.

2024-11-27 03:49 UTC, shamim-emon commented
> Please check [this comment](https://github.com/thunderbird/thunderbird-android/issues/8309#issuecomment-2498120918) for additional requirements for this behavior change.
> 
> Unfortunately, this change doesn't achieve the desired effect.
> 
> 1. `MessagingController.moveOrCopyMessageSynchronous()` is used for all move operations, not just for moving a message to the archive folder. However, we don't want all moved messages to automatically be marked as read.
> 2. Calling `setFlag()` on a `LocalMessage` instance will only mark the message as read locally, not on the server.
> 
> `MessagingController` always changes the local message state first, then enqueues a "command" that will perform the message changes on the server. By separating local changes from remote changes the app can be used offline. When connectivity returns the queue of remote operations will be processed.
> 
> There's already `MoveOrCopyFlavor.MOVE_AND_MARK_AS_READ`. Previously, there was no reason for `MessagingController.moveOrCopyMessageSynchronous()` to support this functionality. Now, adding support for `MOVE_AND_MARK_AS_READ` to this method would make it trivial to then change the behavior of only the archive action.
> 
> Please feel free to ask in the developer Matrix room if you have questions on any of this.

@cketti  please let me know if it's alright

2024-11-28 19:42 UTC, cketti commented
I'm sorry. I missed the fact that the archive operation is treated as a move operation basically everywhere. That requires checking the feature flag in a lot of different places. It should just be one. I created #8623 so the feature flag will only have to be checked in one place.

2024-12-03 17:11 UTC, cketti commented
With #8623 merged, please change your approach to modify the relevant code in `ArchiveOperations` instead.

2024-12-03 18:48 UTC, shamim-emon commented
> With #8623 merged, please change your approach to modify the relevant code in `ArchiveOperations` instead.

@cketti Done! please let me know if anything else needed from my end.
Thanks

2024-12-04 14:22 UTC, cketti requested changes

2024-12-04 14:22 UTC, cketti commented on legacy/core/src/main/java/com/fsck/k9/controller/MessagingController.java
`moveOrCopyMessageSynchronous` still needs to be modified to support `MOVE_AND_MARK_AS_READ`. It looks like you accidentally dropped that change.

Please remove all unrelated formatting changes in this file.

2024-12-04 14:22 UTC, cketti commented on legacy/core/src/main/java/com/fsck/k9/controller/ArchiveOperations.kt
> +        }
```suggestion
        val operation = when (featureFlagProvider.provide("move_and_mark_as_read".toFeatureFlagKey())) {
            FeatureFlagResult.Enabled -> MoveOrCopyFlavor.MOVE_AND_MARK_AS_READ
            FeatureFlagResult.Disabled -> MoveOrCopyFlavor.MOVE
            FeatureFlagResult.Unavailable -> MoveOrCopyFlavor.MOVE
        }
```

2024-12-04 15:41 UTC, shamim-emon commented on legacy/core/src/main/java/com/fsck/k9/controller/MessagingController.java
@cketti Done!

2024-12-05 11:07 UTC, cketti approved these changes
Thanks for your pull request :+1:

Sorry for all the changes you needed to make to this branch. I added a couple of minor changes to avoid additional back and forth.

Right now this feature is disabled. The team will enable it for development and beta versions soon.

2024-12-05 11:54 UTC, merged