Initial focus in message compose screen
thunderbird/thunderbird-android pull request #8664
Opened 2024-12-11 03:53 UTC by shamim-emon

- Deals with initial focus point on mail compose screen
- fixes #7635

2025-01-30 11:15 UTC, wmontwe requested changes
For future changes: I think breaking down the code changes into separate commits would help us to review your changes better. Consider applying each change individually: move Java to a new class, then convert to Kotlin, and finally refactor. 

Besides that it works as expected and it seems that the corner cases still work.

Just the `RecipientMvpView` doesn't need to be a member of `MessageCompose` as it's only needed during `onCreate`

2025-01-31 04:45 UTC, shamim-emon commented on legacy/ui/legacy/src/main/java/com/fsck/k9/activity/MessageCompose.java
> +    private RecipientMvpView recipientMvpView;
Done

2025-01-31 04:45 UTC, shamim-emon commented on legacy/ui/legacy/src/main/java/com/fsck/k9/activity/MessageCompose.java
> +        recipientMvpView = new RecipientMvpView(this);
Done

2025-01-31 04:45 UTC, shamim-emon commented on legacy/ui/legacy/src/main/java/com/fsck/k9/activity/MessageCompose.java
> +
Done

2025-01-31 04:46 UTC, shamim-emon commented on legacy/ui/legacy/src/main/java/com/fsck/k9/ui/compose/IntentDataMapper.kt
> +class IntentDataMapper {
Once this is merge and `IntentDataMapper ` is available in develop. I will create a ticket for this

2025-01-31 21:33 UTC, merged

2025-02-04 03:05 UTC, shamim-emon commented on legacy/ui/legacy/src/main/java/com/fsck/k9/ui/compose/IntentDataMapper.kt
> +class IntentDataMapper {
@wmontwe here is the [issue ](https://github.com/thunderbird/thunderbird-android/issues/8794)to cover unit tests. Please let me know if you have any comment/suggestion on this. Thanks