Fix: Reduce logo size and ensure it resizes dynamically and fits all screen sizes
thunderbird/thunderbird-android pull request #8710
Opened 2024-12-30 16:05 UTC by SttApollo

Fixes #8458

### Description
This PR addresses #8458 where the logo on the onboarding screen flattened the text below. The `WelcomeLogo` composable has been updated to ensure dynamic resizing using `BoxWithConstraints` ensuring that the logo scales proportionally based on screen dimensions and fits properly without overlapping or pushing other components off-screen.

### Changes Made
- Updated `WelcomeLogo` to use `BoxWithConstraints` for adaptive sizing.
- Limited logo and circle sizes to a maximum based on screen width.
- Ensured `LazyColumnWithHeaderFooter` components are unaffected by the logo's size.
- Verified compatibility across various screen sizes (small, medium, large, and tablets).

### Testing
- Tested on multiple screen sizes to ensure no scrolling is required and all components fit properly.

### Visual Example
![Screenshot 2024-12-29 at 3 33 02 PM](https://github.com/user-attachments/assets/b41cb34e-b6d0-4ae1-a952-f1a353f8c54b)
![Screenshot 2024-12-29 at 3 28 56 PM](https://github.com/user-attachments/assets/8c7579c3-1b94-4dc3-a811-102f8d67ee2d)
![Screenshot 2024-12-29 at 3 29 19 PM](https://github.com/user-attachments/assets/a550ceb2-3b50-4a52-8afa-9c6111a4ad34)

2025-01-09 17:53 UTC, wmontwe reviewed
@SttApollo This implementation reduces the logo size across all screen sizes, which diverges from the original design intention of making it prominent. To fix this, I suggest two changes:

1. Slighlty reduce the logo size from its original values to have more room in general.
2. Only use the shrinking logic when a certain maxWidth threshold is reached.

Given the impracticality of fitting all page elements on every screen size, especially very small phones and in landscape mode, I think it would be more effective to use a scroll indicator in these cases.

2025-02-06 21:22 UTC, SttApollo commented
Hii @wmontwe - thank you for your patience. I slightly reduced the logo size and added a custom scroll indicator ( I couldn't find it in the project files and wasn't sure if I could add additional libraries). 

Below are additional notes, brief screen recordings and screenshots to explain this implementation. Please let me know your thoughts and I'll adjust accordingly again, as needed. 

- Custom Scroll indicator caches item  heights using onGloballyPositioned for accurate scroll behavior 
- Inserted a spacer at index=3, ensuring small phones register sufficient overflow for the scrollbar logic to prevent situations where the footer is just slightly cut off from the screen (noticed that issue when testing on smaller devices)
- Maintained vertical space evenly design [
![Screenshot 2025-02-06 at 3 33 52 PM](https://github.com/user-attachments/assets/75afd714-2bb4-479b-ab6a-1a0a40f93893)
![Screenshot 2025-02-06 at 11 05 44 AM](https://github.com/user-attachments/assets/338c1301-0872-4b47-8491-0e39e0428d21)
![SmallPhonee](https://github.com/user-attachments/assets/e6d3b5a2-6069-4be4-8478-0730f640a5df)
[Pixel3.webm](https://github.com/user-attachments/assets/36a5fefd-9cc0-4046-b0b9-3fea42858b63)
[Pixel9ProXL.webm](https://github.com/user-attachments/assets/c3597091-cc13-4e63-9881-0144b9bf4a4f)
](url)

2025-02-18 16:27 UTC, SttApollo commented
Hi @wmontwe! I was trying to make sure the commit passes detekt, so I moved the scroll indicator function to a different file and shortened the welcome content. Do you want me to keep working on these changes or revert to the last commit state?

2025-02-19 11:29 UTC, wmontwe commented
@SttApollo I rebased the pull-request on the latest version of main.

I tried the solution, but I see some performance issues with the scroll indicator that causes compose to redraw a lot. 

I checked if there is another solution available, but not really. Worst case without the indicator, but I would like to look into it a bit.

2025-02-20 20:23 UTC, SttApollo commented
> @SttApollo I rebased the pull-request on the latest version of main.
> 
> I tried the solution, but I see some performance issues with the scroll indicator that causes compose to redraw a lot.
> 
> I checked if there is another solution available, but not really. Worst case without the indicator, but I would like to look into it a bit.

Sounds good - I'll hold until further. Perhaps, I can look at other bugs I can be assigned to.

2025-03-06 07:01 UTC, kewisch commented
@wmontwe any updates on this? I know you've been out a bit, when you have a chance to get back to it I'd appreciate!

2025-03-06 18:34 UTC, wmontwe commented
@SttApollo Unfortunately, my attempts to enhance the scroll indicator were unsuccessful. It seems this requires significant efforts and should be a separate task.

I think it's best to remove it for now and I have a look at the version without scroll indicator.

> Sounds good - I'll hold until further. Perhaps, I can look at other bugs I can be assigned to.

Is there a specific area of interest (UI etc)?

2025-03-06 21:30 UTC, SttApollo commented
I have removed the scroll indicator @wmontwe. And yes the UI for my first few issues! Is there anything in [#8812](https://github.com/thunderbird/thunderbird-android/issues/8812) epic I may be able to support? Also open to other suggestions you may have!

2025-03-12 17:52 UTC, wmontwe requested changes
I think the size changes are working very good. Just the logo and title should be part of the header section. The Box around the layout is not needed, as it prevents the list to draw it's content to full screen size.

You could fix the formatting issues by running `./gradlew spotlessApply`. Run `./gradlew detekt` to find other issues.

2025-03-12 17:52 UTC, wmontwe commented on feature/onboarding/welcome/src/main/kotlin/app/k9mail/feature/onboarding/welcome/ui/WelcomeContent.kt
> +
I guess your using a different code format. Just run `./gradlew spotlessApply` to streamline your changes with our code format. If you update the branch to current main, Spotless is also way quicker.

2025-03-12 17:52 UTC, wmontwe commented on feature/onboarding/welcome/src/main/kotlin/app/k9mail/feature/onboarding/welcome/ui/WelcomeContent.kt
> +                )
The box is not needed and instead the `fillMaxSize` should be applied to the `LazyColumnWithHeaderFooter`. The `WelcomeTitleItem` should move into the header section to group logo and title together.

```suggestion
    Surface(
        modifier = modifier,
    ) {
        ResponsiveContent {
            LazyColumnWithHeaderFooter(
                modifier = Modifier.fillMaxSize(),
                verticalArrangement = Arrangement.SpaceEvenly,
                header = {
                    WelcomeHeaderSection(title = appName)
                },
                footer = {
                    WelcomeFooterSection(
                        showImportButton = showImportButton,
                        onStartClick = onStartClick,
                        onImportClick = onImportClick,
                    )
                },
                content = {
                    item { WelcomeMessageItem() }
                },
            )
```

2025-03-12 17:52 UTC, wmontwe commented on feature/onboarding/welcome/src/main/kotlin/app/k9mail/feature/onboarding/welcome/ui/WelcomeContent.kt
> +
We always add the Modifier to composables. The title could be added here.

```suggestion
    title: String,
    modifier: Modifier = Modifier,
```

2025-03-12 17:52 UTC, wmontwe commented on feature/onboarding/welcome/src/main/kotlin/app/k9mail/feature/onboarding/welcome/ui/WelcomeContent.kt
> +        WelcomeLogo()
Add the title here.

```suggestion
        WelcomeLogo()
        WelcomeTitleItem(title = title)
```

2025-03-12 17:52 UTC, wmontwe commented on feature/onboarding/welcome/src/main/kotlin/app/k9mail/feature/onboarding/welcome/ui/WelcomeContent.kt
> +            contentAlignment = Alignment.Center,
Replace the box by a column.
```suggestion
    Column(
        modifier = modifier
            .fillMaxWidth()
            .defaultItemModifier()
            .padding(top = MainTheme.spacings.double),
            contentAlignment = Alignment.Center,
            .padding(top = MainTheme.spacings.quadruple),
        verticalArrangement = Arrangement.spacedBy(MainTheme.spacings.double),
        horizontalAlignment = Alignment.CenterHorizontally,
```

2025-03-12 17:52 UTC, wmontwe commented on feature/onboarding/welcome/src/main/kotlin/app/k9mail/feature/onboarding/welcome/ui/WelcomeContent.kt
> +    title: String,
Please add the modifier here:

```suggestion
    title: String,
    modifier: Modifier = Modifier,
```

2025-03-12 17:52 UTC, wmontwe commented on feature/onboarding/welcome/src/main/kotlin/app/k9mail/feature/onboarding/welcome/ui/WelcomeContent.kt
> +        modifier = Modifier
```suggestion
        modifier = modifier
```

2025-03-12 17:52 UTC, wmontwe commented on feature/onboarding/welcome/src/main/kotlin/app/k9mail/feature/onboarding/welcome/ui/WelcomeContent.kt
> +){
Please add the modifier here:

```suggestion
    modifier: Modifier = Modifier,
) {
```

2025-03-15 20:56 UTC, SttApollo commented
@wmontwe thank you, done!

2025-03-17 09:49 UTC, wmontwe approved these changes
Thank you!

2025-03-17 10:37 UTC, merged